# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='publish',
            field=models.DateTimeField(blank=True),
        ),
    ]
